name: base
bake_time: 12-13
bake_temp: 350
ingredients:
  flour: "2 cups"
  granulated_sugar: "1 cup"
  butter: "1/2 cup"
  eggs: "2 egg"
  vanilla: "1 teaspoon"
  baking_soda: "1 teaspoon"
  salt: "1/2 teaspoon"
steps:
  1: In a large mixing bowl, beat butter and sugars until smooth and fluffy
  2: Add eggs and vanilla; beat until well blended
  3: Add flour, baking soda, and salt; mix until no flour streaks; do not overmix
  4: Chill dough for 15-30 minutes
  5: Preheat oven to {bake_temp}°F
  6: Line baking sheets with parchment paper
  7: Form tablespoon-sized dough balls and place 2 inches apart; 12 per sheet
  8: Bake {bake_time} minutes, or until cookies lose their shiny appearance
  9: Let cool for about 10 minutes; store for up to a week in airtight container
