name: base
bake_time: 12-13
bake_temp: 350
ingredients:
  flour: "2 cups"
  granulated_sugar: "1 cup"
  butter: "1/2 cup"
  eggs: "2 egg"
  vanilla: "1 tsp"
  baking_soda: "1 tsp"
  salt: "1/2 tsp"
steps:
  1: Beat butter and sugars until smooth and fluffy
  2: Add eggs and vanilla; beat until well blended
  3: Add flour, baking soda and salt; beat until no flour streaks, no more
  4: Place dough in fridge for 15-30 minutes
  5: Preheat oven to {bake_temp}°F
  6: Line baking sheets with parchment paper
  7: Form tablespoon-sized dough balls and place 2in apart on sheet (12 per sheet)
  8: Bake just until cookies lose their shiny appearance, {bake_time} minutes
  9: Let cookies cool for about 10 minutes before eating
